### ISSUE TITLE
Unable to Load image

### ISSUE THREAD

**Issue by arthur3672** [prasadus92/face-recognition#1]
May i know what type of file type of image loaded and the resolution of the image

**Comment by prasadus92** [comment]
Hey Arthur,

I am not sure if you resolved the "missing package" error by yourself. I was trying too. Regarding the image type, please use PNG format. For my testing, I actually used [Bosphorus Dataset](http://bosphorus.ee.boun.edu.tr/default.aspx).

Hope this helps.

Best,
Prasad

**Comment by prasadus92** [comment]
Closing this issue as there is no additional response.
